apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name : todoapptest
        image: piyush1008/todo-app-test:6
        ports:
        - containerPort: 3000
        # volumeMounts:
        #   - name: env-file
        #     readOnly: true
        #     mountPath: "/app/secret"
        env:
        - name : PORT
          valueFrom: 
            secretKeyRef:
              name: backend-secret
              key: port
        - name : DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: backend-secret
              key: database_url
      # volumes:
      # - name: env-file
      #   secret:
      #     secretName: backend-secret


---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30007
  type: NodePort