apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name : todoapptest
        image: piyush1008/todo-app-test:2
        ports:
        - containerPort: 3000
        volumeMounts:
          - name: env-file
            readOnly: true
            mountPath: "/app/secret"

        # - name : PORT
        #   valueFrom: 
        #     configMapKeyRef:
        #       name: backend-config
        #       key: port
        # - name : DATABASE_URL
        #   valueFrom:
        #     secretKeyRef:
        #       name: backend-secret
        #       key: database_url
      volumes:
      - name: env-file
        secret:
          secretName: backend-secret